modify build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -48,33 +48,6 @@ jobs:
       - name: Checkout
         uses: actions/checkout@main
 
-      - name: get config
-        run: |
-          # config 命名规则: <repo>;<owner>;<name>.config
-
-          config="${{ matrix.config }}"
-          config=${config/.config/}            # 去掉 .config 后缀
-          array=(${config//;/ })               # ;号分割
-
-          if [ ${#array[@]} -ne 3 ]; then
-            echo "${{ matrix.config }} name error!"
-            exit 1
-          fi
-
-          echo "CONFIG_REPO=${array[0]}" >> $GITHUB_ENV
-          echo "CONFIG_OWNER=${array[1]}" >> $GITHUB_ENV
-          echo "CONFIG_NAME=${array[2]}" >> $GITHUB_ENV
-
-          if [ "${array[0]}" == "openwrt" ]; then
-            echo "REPO_URL=https://github.com/openwrt/openwrt" >> $GITHUB_ENV
-            echo "REPO_BRANCH=master" >> $GITHUB_ENV
-          fi
-
-          if [ "${array[0]}" == "lede" ]; then
-            echo "REPO_URL=https://github.com/coolsnowwolf/lede" >> $GITHUB_ENV
-            echo "REPO_BRANCH=master" >> $GITHUB_ENV
-          fi
-
       - name: Init Env
         env:
           DEBIAN_FRONTEND: noninteractive
@@ -105,86 +78,105 @@ jobs:
             make && sudo make install
           popd
 
-      - name: Clone source code
+      - name: make
         run: |
-          df -hT $PWD
-          cd ~
+          WORKSPACE=${GITHUB_WORKSPACE:-$(pwd)}
+          release="${{ env.release }}"
+          script="${{ env.diyscript }}"
+          config="${{ matrix.config }}"               # config 命名规则: <repo>;<owner>;<name>.config
+          CONFIG=${config/.config/}                   # 去掉 .config 后缀
+          CONFIG_ARRAY=(${config//;/ })               # ;号分割
 
-          git clone ${{ env.REPO_URL }} -b ${{ env.REPO_BRANCH }} openwrt
-
-          if [ -d "openwrt/package/lean/r8125" ]; then
-            rm -rf openwrt/package/lean/r8125
+          if [ ${#CONFIG_ARRAY[@]} -ne 3 ]; then
+            echo "${config} name error!"
+            exit 1
           fi
 
-      - name: feeds
-        run: |
-          cd ~/openwrt 
-          sed -i '1 i src-git ing https://github.com/wjz304/openwrt-packages;${{ env.CONFIG_REPO }}' feeds.conf.default
+          CONFIG_REPO="${CONFIG_ARRAY[0]}"
+          CONFIG_OWNER="${CONFIG_ARRAY[1]}"
+          CONFIG_NAME="${CONFIG_ARRAY[2]}"
+
+          if [ "${CONFIG_REPO}" == "openwrt" ]; then
+            REPO_URL="https://github.com/openwrt/openwrt"
+            REPO_BRANCH="master"
+          fi
+
+          if [ "${CONFIG_REPO}" == "lede" ]; then
+            REPO_URL="https://github.com/coolsnowwolf/lede"
+            REPO_BRANCH="master"
+          fi
+
+          if [ ! -d ${CONFIG_REPO} ]; then
+            git clone ${REPO_URL} -b ${REPO_BRANCH} ${CONFIG_REPO}
+            if [ -d "${CONFIG_REPO}/package/lean/r8125" ]; then
+              rm -rf ${CONFIG_REPO}/package/lean/r8125
+            fi
+          fi
+
+          # root.
+          export FORCE_UNSAFE_CONFIGURE=1
+
+          pushd ${CONFIG_REPO}
+          git pull
+
+          # feeds
+          sed -i "/src-git ing /d; 1 i src-git ing https://github.com/wjz304/openwrt-packages;${CONFIG_REPO}" feeds.conf.default
 
           ./scripts/feeds update -a
-
           ./scripts/feeds install -a
-
           ./scripts/feeds uninstall `grep Package ./feeds/ing.index | awk -F': ' '{print $2}'`
           ./scripts/feeds install -p ing -a
 
-      - name: Make config
-        run: |
-          # $GITHUB_WORKSPACE == ${{ github.workspace }}
-          cd ~/openwrt
+          cp -f "${WORKSPACE}/${config}" "./.config"
+          cp -f "${WORKSPACE}/${script}" "./diy.sh"
 
-          [ -e "$GITHUB_WORKSPACE/${{ matrix.config }}" ] && cp "$GITHUB_WORKSPACE/${{ matrix.config }}" "./.config"
-
-          if [ -e "$GITHUB_WORKSPACE/${{ env.diyscript }}" ]; then
-            chmod +x "$GITHUB_WORKSPACE/${{ env.diyscript }}"
-            "$GITHUB_WORKSPACE/${{ env.diyscript }}" "${{ env.CONFIG_REPO }}" "${{ env.CONFIG_OWNER }}"
-          fi
+          chmod +x "./diy.sh"
+          "./diy.sh" "${CONFIG_REPO}" "${CONFIG_OWNER}"
 
           make defconfig
 
-      - name: Check and Push config
-        run: |
-          git pull
-          [ -e "${{ matrix.config }}" ] && cp ~/openwrt/.config "${{ matrix.config }}"
-          status=$(git status -s | grep "${{ matrix.config }}" | awk '{printf $2}')
-          if [ -n "${status}" ]; then
-            git add "${status}"
-            git commit -m "update $(date +%Y-%m-%d" "%H:%M:%S)"
-            git push -f
+          if [ "$GITHUB_ACTIONS" == "true" ]; then
+            pushd ${WORKSPACE}
+            git pull
+            cp -f ${WORKSPACE}/${CONFIG_REPO}/.config "${WORKSPACE}/${config}"
+            status=$(git status -s | grep "${config}" | awk '{printf $2}')
+            if [ -n "${status}" ]; then
+              git add "${status}"
+              git commit -m "update $(date +%Y-%m-%d" "%H:%M:%S)"
+              git push -f
+            fi
+            popd
           fi
-
-      - name: Compile the firmware
-        run: |
-          cd ~/openwrt
 
           echo -e "download package"
           make download -j8 V=s
 
-          find dl -size -1024c -exec ls -l {} \;
-          find dl -size -1024c -exec rm -f {} \;
+          # find dl -size -1024c -exec ls -l {} \;
+          # find dl -size -1024c -exec rm -f {} \;
 
           echo -e "$(nproc) thread compile"
-          # export FORCE_UNSAFE_CONFIGURE=1 # root
           make -j$(nproc) V=s || make -j1 V=s
 
-          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > device_name
-          [ -s device_name ] && echo "device_name=_$(cat device_name)" >> $GITHUB_ENV
-
-      - name: Organize files
-        if: success() && !cancelled()
-        run: |
-          df -hT
-          cd ~/openwrt/bin/targets/*/*
+          DEVICE_NAME=$(grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/')
+     
+          pushd bin/targets/*/*
           ls -al
 
           # sed -i '/buildinfo/d; /\.bin/d; /\.manifest/d' sha256sums
           rm -rf packages *.buildinfo *.manifest *.bin sha256sums
 
-          filename=${{ env.CONFIG_REPO }}-${{ env.CONFIG_NAME }}-${{ env.release }}.zip
+          filename=${CONFIG_REPO}-${CONFIG_NAME}-${release}.zip
 
           gzip *.img 2>/dev/null || true
           zip -q -r ${filename} *
-          echo "firmware=$PWD/${filename}" >> $GITHUB_ENV
+
+          if [ "$GITHUB_ACTIONS" == "true" ]; then
+            echo "firmware=$(pwd)/${filename}" >> $GITHUB_ENV
+          else
+            mv -f ${filename} ${WORKSPACE}
+          fi
+          popd  # bin/targets/*/*
+          popd  # ${CONFIG_REPO}
 
       - name: Upload firmware to release
         uses: softprops/action-gh-release@v1
